### PR TITLE
ESLint + fix text color property having no effect + extract css

### PR DESCRIPTION
**Pull request by Tofandel**
- Auto linting + formatting
- Fix the text color setting having no effect
- Replace scoping css and js bundling by normal css import to avoid heavy dom (see readme.md)

### CODE REVIEW

**Comment by MatheusrdSantos** [comment]
Hi, @Tofandel 
I found a problem when testing your pull request.
I got this message when run ```yarn serve```

image

Furthermore, when I installed less-loader another error still appearing.

image

**Comment by Tofandel** [comment]
I'll fix this tomorrow but I think you're missing less as well
`npm install -D less-loader less`
Forgot that I had less installed globally on npm so I forgot to check that it was on the package

**Comment by Tofandel** [comment]
It's fixed, I also added a new functionality for loading messages when you reach the top of the scroll (documented in readme and with a test in the App.vue)
Would be cool to add some unit tests now

**Comment by MatheusrdSantos** [comment]
I really liked the upload functionality. 
That is a good idea to add some unit test. I'll think about it in future implementations.
Thank you again!

**Pull request merged**
