### PR TITLE
timestampConfig and viewed messages

### PR DESCRIPTION
**Pull request by vonec**
1. added class to viewed messages
2. added timestampConfig to change timestamp format and option to enable relative timestamp

### CODE REVIEW

**Comment by MatheusrdSantos** [comment]
Hi, @vonec! You forgot to declare the prop 'timestampConfig' in the following components:
- OtherMessage
- MyMessage
- MessageDisplay

**Comment by MatheusrdSantos** [comment]
If you prefer, permit me to edit your pull request, and then I'll fix it.
You can allow commits by checking a checkbox on the right panel of the PR.

**Comment by vonec** [comment]
just noticed, its already allowed but anyway I'm making those changes now ...

**Comment by vonec** [comment]
* There’s no date on the messages…can we include date along with time or can it be like WhatsApp, where date appears only once, above the first message for that day?

**Comment by zayda3** [comment]
> * There’s no date on the messages…can we include date along with time or can it be like WhatsApp, where date appears only once, above the first message for that day?

Taking into account that this chat allows us to differentiate the read and unread messages as in WhatsApp, I think that, if possible, it should be done following that reference.

**Comment by MatheusrdSantos** [comment]
Thanks, @vonec! I'll merge your PR and publish a new release.

**Comment by vonec** [comment]
Thank you :)

**Comment by vonec** [comment]
build is failing ... i think something is wrong with the release.

This dependency was not found:  error

**Comment by MatheusrdSantos** [comment]
I ran the wrong command to build the production version. I guess it is solved. Just update to 1.2.2.

**Comment by vonec** [comment]
thank you

**Pull request merged**
