### PR TITLE
watch all props

### PR DESCRIPTION
**Pull request by Qanah**
Please check my pull request

### CODE REVIEW

**Comment by MatheusrdSantos** [comment]
Hi,
could you explain what you have implemented or fixed in this pull request?

**Comment by MatheusrdSantos** [comment]
I reviewed your changes, but I didn't understand why to watch all the props.

**Comment by Qanah** [comment]
imagine you want to implement web WhatsApp then your chat object will be like this
```
selectedChat: {
        id: 1,
        title: 'My chat title',
        participants: [ ... ],
        messages: [ ... ]
},
chats: [
      {
        id: 1,
        title: 'My first chat title',
        participants: [ ... ],
        messages: [ ... ]
      },
      {
        id: 2,
        title: 'My sacand chat title',
        participants: [ ... ],
        messages: [ ... ]
      },
]
```
Screen Shot 2019-12-01 at 9 08 43 AM

```
<Chat
          v-if="selectedChat.id"
          :myself="myself"
          :chat-title="selectedChat.title"
          :participants="selectedChat.participants"
          :messages="selectedChat.messages"
          :on-type="onType"
          :on-message-submit="onMessageSubmit"
          :placeholder="placeholder"
          :colors="colors"
          :border-style="borderStyle"
          :hide-close-button="hideCloseButton"
          :close-button-icon-size="closeButtonIconSize"
          :submit-icon-size="submitIconSize"
          :load-more-messages="toLoad.length > 0 ? loadMoreMessages : null"
          :async-mode="asyncMode"
        />
```

for placeholder you can use it to i18n

**Comment by Tofandel** [comment]
While this does make sense, it is not needed,

To reload a vue components data you should have just used the key prop
Eg:
```html
<Chat
          v-if="selectedChat.id"
          :key="selectedChat.id"
...
 />
```

This would have done what you were looking for

**Comment by MatheusrdSantos** [comment]
I've reproduced the error, that's a problem. The @Tofandel's solution is easier to implement and worked pretty fine for me. However, we could have some other problems when using this solution ``` :key="selectedChat.id" ```. Because if you have only one chat and want to change just the chat title, the component won't update since the chat id still the same.

So I'll accept this PR and let the component watch its properties.

**Pull request merged**
